# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Fail if required Syncthing settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - syncthing_identifier
    - syncthing_uid
    - syncthing_gid
    - syncthing_hostname
    - syncthing_path_prefix
    - syncthing_container_network

- name: Fail if required Syncthing basic auth enabled, but no credentials specified
  ansible.builtin.fail:
    msg: >-
      When enabling Basic Auth for Syncthing (`syncthing_basicauth_enabled`), you need to provide at least one set of
      credentials in `syncthing_basicauth_credentials` or `syncthing_basicauth_htpasswds`.
  when: "syncthing_basicauth_enabled and (syncthing_basicauth_credentials | length + syncthing_basicauth_htpasswds | length == 0)"

- when: syncthing_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Syncthing Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - syncthing_container_labels_traefik_hostname
        - syncthing_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `syncthing_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if syncthing_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          syncthing_container_labels_traefik_path_prefix (`{{ syncthing_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/syncthing`).
      when: "syncthing_container_labels_traefik_path_prefix != '/' and syncthing_container_labels_traefik_path_prefix[-1] == '/'"
